# Removes data generated by providers_process_raw.py
# to allow re-write of new files.  Particularly important
# when need to change file extensions or naming conventions
# of what is loaded. 
rm -Rf ../docs/data/dental/provider/autosug
rm -Rf ../docs/data/dental/provider/index
rm -Rf ../docs/data/dental/provider/recs
rm -Rf ../docs/data/dental/provider/search
